[package]
name = "triad-window"
version = "0.1.0"
edition = "2024"

[dependencies]
triad-gpu = { path = "../triad-gpu" }
winit = { version = "0.30", features = ["rwh_05"] }
glam = "0.30"
pollster = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
bytemuck = { version = "1.24", features = ["derive"] }
tracing-tracy = { version = "0.11", optional = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
egui-winit = { version = "0.33.3", default-features = false, features = ["links", "wayland", "x11"] }
thiserror = "1.0"

[features]
default = []
tracy = ["tracing-tracy"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "Element", "HtmlCanvasElement", "Window"] }
